### ISSUE TITLE
Every change orientation load my app from start

### ISSUE THREAD

**Issue by reut-cambium** [honza889/cordova-plugin-kiosk#1]
I check before I add the plugin,and it work good. But after adding the plugin,every orientation change its reload. Sometimes show white page with:"press to continue.. " and then load.

The plugin very good but I need the app in portrait and landscape too.
Thanks,
Reut

**Comment by thaarok** [comment]
In the end the problem was trivial - there was missing `android:configChanges` in activity definition, so activity was restarted on every configuration change. Should be fixed in master now.

Please retest and close this issue if it ok now. Don't forgot `cordova platform rm android` + `cordova platform add android` to changes take effect.

**Comment by DavidSalzer** [comment]
Thanks for fix it. I try to check your plugin now, but it's make my app collapse.
My app work good, but when I click on home button, it's open popup, I choose my app to be the luncher, and then the app collapse.
Can you check it?

**Comment by reut-cambium** [comment]
Now it's work. 
Thanks.

**Comment by thaarok** [comment]
Thanks.
@DavidSalzer Can you test https://github.com/honza889/cordova-kiosk-demo on your phone? If this app works for you, try compare what is different in your app and feel free to open new issue here.
