### ISSUE TITLE
update app in kiosk mode

### ISSUE THREAD

**Issue by hrobar** [honza889/cordova-plugin-kiosk#17]
Hello,
I have plugin https://github.com/vaenow/cordova-plugin-app-update for udpate app (download and install apk without google play).
 I haven´t install APK after download in Kiosk mode. 
What can i do?

**Comment by thaarok** [comment]
@hrobar Maybe is the problem related to opening AlertDialog, meanwhile KioskActivity is closing any system dialog which appears on the screen?
Also, if you are modifying Cordova activity,  you need to do the same modification to the KioskActivity.

Need more info what happens if I should help. You can reopen which you will discover which part of you plugin is affected.

**Comment by thaarok** [comment]
> What can i do?

You can add logging messages into your plugin and check the log after failing - discover which part is failing.
