### ISSUE TITLE
Can't turn off device

### ISSUE THREAD

**Issue by ramezrafla** [honza889/cordova-plugin-kiosk#18]
Thanks @honza889 for this amazing plugin.

All works as planned, except .. we can't turn off the device :) the plugin closes the popup as soon as it appears. Any advice? I believe it's the Pause event, but don't know where to handle it in your Java. Any help would be greatly appreciated (Also, I do expect this to be a common request, even Kiosk devices need to be shut down).

**Comment by thaarok** [comment]
To turn off the device you need to exit the kiosk using `KioskPlugin.exitKiosk();`

**Comment by ramezrafla** [comment]
Thank you @honza889 
I want to give the user the ability to turn off the device with the hardware buttons. Is that possible?

**Comment by thaarok** [comment]
Sorry, it is not possible to turn device off from android application which is not system application - it would require rooted device - which is out of aim of this plugin.
For more info you can check:
http://stackoverflow.com/questions/3745523/programmatically-switching-off-android-phone
(but feel free to send pull request if you will implement it)

**Comment by paranoico** [comment]
Hello @ramezrafla , we use this component in our mobile app.
Users are told to enable screen locking, so if they suspend android phone, then power button works as expected and device can be turned off or reseted.
And, for your information, plugin closes pop since it send a message to close all system dialogs as soon as it loses focus. Cannot remember code line numbers now.
