### ISSUE TITLE
Launch another app when in kiosk mode

### ISSUE THREAD

**Issue by ramezrafla** [honza889/cordova-plugin-kiosk#22]
I banged my head for a while and am close to giving up so I thought I would ask for help from the experts.

I have an app that is in kiosk mode using this plugin. However, we need to be able to launch other apps from within our app, and then when done, we come back to the kiosk app. When I use intents to launch another app our app am still in the front. Even when we call `moveToBack` -- don't know what to do?

Is it at all feasible? This is beyond my skillset. Thanks

**Comment by paranoico** [comment]
Hello @ramezrafla 
There are some options:
- Currently we created a new custom plugin to start the new Intent using Java.
- Before that, we used a component like the following one (we decided to use our own plugin since we make some validations before start new app):
  - https://github.com/sindresorhus/opn
  - https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url

Regards.

**Comment by ramezrafla** [comment]
Thanks @paranoico 
Your links are for desktop, and your plugin is for Android. Am I missing something?

**Comment by paranoico** [comment]
@ramezrafla Yes, we use Meteor, so our plugin is for Android specifically for now.
The tool https://github.com/sindresorhus/opn is cross platform and iyes we have tested it on Desktop.
You r correct.

**Comment by ramezrafla** [comment]
Thanks!
